CREATE TABLE PERSON (
  ID    INTEGER PRIMARY KEY,
  FIRST_NAME  VARCHAR(50),
  LAST_NAME  VARCHAR(50),
  EMAIL VARCHAR(50),
  CONTACT_NUMBER VARCHAR(15)
);


CREATE TABLE BOOK (
  ID     INTEGER PRIMARY KEY,
  TITLE  VARCHAR(1024),
  AUTHOR VARCHAR(50),
  ISBN   VARCHAR(50),
  PERSON_ID INTEGER,
  foreign key (PERSON_ID) references PERSON(ID)
);

